<?php

namespace App\Http\Controllers\Quantri\giaovien;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Teacher;
use DateTime;

class listController extends Controller
{
    public function listT()
    {
        $data=Teacher::get()->toArray();
        return view('quantri.teacher.list',['data'=>$data]); // TODO: Change the autogenerated stub
    }
    public function addT(Request $request)
    {
        $gv=new Teacher();
        $gv->name=$request->name;
        $gv->slug=str_slug($request->name,"-");
        $gv->email=$request->email;
        $gv->sdt=$request->sdt;
        $gv->diachi=$request->diachi;
        $gv->hocvan=$request->hocvan;
        $gv->ngaysinh=$request->ngaysinh;
        $gv->td=$request->td;
        $gv->kn=$request->kn;
        $gv->khanang=$request->khanang;
        $gv->sex=$request->sex;
        $gv->created_at=new DateTime();
        $gv->save();
        return redirect()->route('listT')->with(['flash_level'=>'result_msg','flash_message'=>'Add item succsess']);
        // TODO: Change the autogenerated stub
    }
    public function deleteT($id)
    {
        $gv=Teacher::find($id);
        $gv->delete();
        return redirect()->route('listT')->with(['flash_level'=>'result_msg','flash_message'=>'Delete item succsess']);
        // TODO: Change the autogenerated stub
    }
    public function detailT($id)
    {
        $data=Teacher::get()->where('id','=',$id)->toArray();
        return view('quantri.teacher.detail',['data'=>$data]); // TODO: Change the autogenerated stub
    }
}
