<?php

namespace App\Http\Controllers\Quantri\lophoc;

use DateTime;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Lophoc;

class listController extends Controller
{
    public function listClass()
    {
        $data=Lophoc::get()->toArray();
        return view('quantri.lophoc.list',['data'=>$data]);
    }
    public function addClass(Request $request)
    {
        $lophoc=new Lophoc();
        $lophoc->name=$request->name;
        $lophoc->slug=str_slug($request->name,"-");
        $lophoc->status=$request->status;
        $lophoc->created_at=new DateTime();
        $lophoc->save();
        return redirect()->route('listClass')->with(['flash_level'=>'result_msg','flash_message'=>'Add item success !']);
        // TODO: Change the autogenerated stub
    }
    public function editClass($id, Request $request)
    {
        $lophoc=Lophoc::find($id);
        $lophoc->name=$request->name;
        $lophoc->slug=str_slug($request->name,"-");
        $lophoc->status=$request->status;
        $lophoc->updated_at=new DateTime();
        $lophoc->save();
        return redirect()->route('listClass')->with(['flash_level'=>'result_msg','flash_message'=>'Edit item success !']);
        // TODO: Change the autogenerated stub
    }
    public function deleteClass($id, Request $request)
    {
        $lophoc=Lophoc::find($id);
        $lophoc->delete();
        return redirect()->route('listClass')->with(['flash_level'=>'result_msg','flash_message'=>'Delelte item success !']);// TODO: Change the autogenerated stub
    }
}
