<?php

namespace App\Http\Controllers\Quantri\thanhvien;

use App\Models\Phancong;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Student;
use App\Models\Lophoc;
use App\Models\Monhoc;
use DateTime;
use Illuminate\Support\Facades\DB;

class listController extends Controller
{
    public function listUsers(){
        $data=Student::paginate(15);
        $lop=Lophoc::get()->toArray();
        return view('quantri.student.list',['data'=>$data,'lop'=>$lop]);
    }
    public function addUsers(Request $request)
    {
        $u=new Student();
        $u->name=$request->name;
        $u->email=$request->email;
        $u->diachi=$request->diachi;
        $u->sdt=$request->sdt;
        $u->lop_id=$request->lop_id;
        $u->sex=$request->sex;
        $u->ngaysinh=$request->ngaysinh;
        $u->ycgt=$request->ycgt;
        $u->yctd=$request->yctd;
        $u->mon_id=implode(",",array_values($request->mon_id));
        $u->created_at=new DateTime();
        $u->save();
        return redirect()->route('listUsers')->with(['flash_level'=>'result_msg','flash_message'=>'Add item success !']);
        // TODO: Change the autogenerated stub
    }
    public function detailStudent($id)
    {
        $data=Student::with('lophoc')->get()->where('id','=',$id)->toArray();
        $pc=Phancong::select('id')->where('hv_id','=',$id)->get()->toArray();
       // echo "<pre>";print_r($pc);echo "</pre>";
        return view('quantri.student.detail',['data'=>$data,'pc'=>$pc]); // TODO: Change the autogenerated stub
    }
    public function editStudent($id,Request $request)
    {
    	$st=Student::find($id);
    	$st->status=1;
    	$st->save();
    	$pc=Phancong::find($request->hv_id);
        $pc->delete();
    	return redirect()->route('listUsers')->with(['flash_level'=>'result_msg','flash_message'=>'Edit item success !']);
    }

    public function deleteStudent($id)
    {
        $u=Student::find($id); 
        $u->delete();
        return redirect()->route('listUsers')->with(['flash_level'=>'result_msg','flash_message'=>'Delete item success !']);
        // TODO: Change the autogenerated stub
    }
}
