<?php

namespace App\Http\Controllers\Quantri\monhoc;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Monhoc;
use App\Models\Lophoc;
use DateTime;

class listController extends Controller
{
    public function listSubject()
    {
        $lophoc=Lophoc::get()->toArray();
        $data=Monhoc::with('lophoc')->get()->toArray();
//        echo "<pre>";
//        print_r($data);
//        echo "</pre>";
        return view('quantri.monhoc.list',['lophoc'=>$lophoc,'data'=>$data]);// TODO: Change the autogenerated stub
    }
    public function addSubject(Request $request)
    {
        $sub=new Monhoc();
        $sub->name=$request->name;
        $sub->slug=str_slug($request->name,"-");
        $sub->lop_id=$request->lop_id;
        $sub->status=$request->status;
        $sub->created_at=new DateTime();
        $sub->save();
        return redirect()->route("listSubject")->with(['flash_level'=>'result_msg','flash_message'=>'Add item success !']);// TODO: Change the autogenerated stub
    }
    public function editSubject($id, Request $request)
    {
        $sub=Monhoc::find($id);
        $sub->name=$request->name;
        $sub->slug=str_slug($request->name,"-");
        $sub->lop_id=$request->lop_id;
        $sub->status=$request->status;
        $sub->updated_at=new DateTime();
        $sub->save();
        return redirect()->route("listSubject")->with(['flash_level'=>'result_msg','flash_message'=>'Edit item success !']);// TODO: Change the autogenerated stub
    }
    public function delete($id)
    {
        $sub=Monhoc::find($id);
        $sub->delete();
        return redirect()->route("listSubject")->with(['flash_level'=>'result_msg','flash_message'=>'Delete item success !']);// TODO: Change the autogenerated stub
    }
}
