<?php

namespace App\Http\Controllers\Giaodien\page;

use App\Models\Category;
use App\Models\Lophoc;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Student;
use App\Models\About;
use DateTime;

class hocvienController extends Controller
{
    public function hocvien()
    {
        $menu=Category::get()->toArray();
        $lop=Lophoc::get()->toArray();
        $hv=Student::with('lophoc')->take(11)->orderBy('id','desc')->get()->toArray();
        $lop=Lophoc::limit(5)->get()->toArray();
        $about=About::get()->toArray();
        return view('giaodien.page.hocvien',['menu'=>$menu,'lop'=>$lop,'hv'=>$hv,'lop'=>$lop,'about'=>$about]);
        // TODO: Change the autogenerated stub
    }
    public function addhocvien(Request $request)
    {
        $u=new Student();
        $u->name=$request->name;
        $u->email=$request->email;
        $u->diachi=$request->diachi;
        $u->sdt=$request->sdt;
        $u->lop_id=$request->lop_id;
        $u->sex=$request->sex;
        $u->ngaysinh=$request->ngaysinh;
        $u->ycgt=$request->ycgt;
        $u->yctd=$request->yctd;
        $u->mon_id=implode(",",array_values($request->mon_id));
        $u->created_at=new DateTime();
        $u->save();
        return redirect()->route('hocvien')->with(['flash_level'=>'result_msg','flash_message'=>"Bạn Đã Ghi Danh Thành Công ! Vui lòng đợi để chúng tôi liên lạc lại với bạn !"]);
    }
}
