<?php

namespace App\Http\Controllers\Giaodien\page;

use App\Models\Category;
use App\Models\News;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Lophoc;
use App\Models\About;

class tintucController extends Controller
{
    public function tintuc()
    {
        $menu = Category::get()->toArray();
        $news = News::orderBy('id','desc')->paginate(9);
        $lop=Lophoc::limit(5)->get()->toArray();
        $about=About::get()->toArray();
        return view('giaodien/page/tintuc',['menu'=>$menu,'news'=>$news,'lop'=>$lop,'about'=>$about]);
        // TODO: Change the autogenerated stub
    }
}
