<?php

namespace App\Http\Controllers\Giaodien\home;

use App\Models\News;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Slide;
use App\Models\Lophoc;
use App\Models\Monhoc;
use App\Models\About;
use Illuminate\Support\Facades\DB;

class indexController extends Controller
{
    public function index() 
    {
        $menu=Category::get()->toArray();
        $news=News::limit(6)->orderBy('id','desc')->get()->toArray(); 
        $slide=Slide::limit(3)->orderBy('id','desc')->get()->toArray();
        $lop=Lophoc::limit(5)->get()->toArray();
        $about=About::get()->toArray();
        //echo "<pre>";print_r($lop);echo "</pre>";
        return view('giaodien.home.index',
        	['menu'=>$menu,'news'=>$news,'slide'=>$slide,'lop'=>$lop,'about'=>$about]
        	);
        // TODO: Change the autogenerated stub
    }
}
