<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Lophoc extends Model
{
    protected $table = 'giasu_lophoc';
    protected $fillable = [];
    public function monhoc()
    {
        return $this->hasMany('App\Models\Monhoc');
    }
    public function student()
    {
        return $this->hasMany("App\Models\Student"); // TODO: Change the autogenerated stub
    }
    public function file()
    {
        return $this->hasMany('App\Models\File');
    }
}
