<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Monhoc extends Model
{
    protected $table = 'giasu_monhoc';
    protected $fillable = [];
    public function lophoc()
    {
        return $this->belongsTo("App\Models\Lophoc","lop_id"); // TODO: Change the autogenerated stub
    }

}
