<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    protected $table = 'giasu_hocvien';
    protected $fillable = [];
    public function lophoc()
    {
        return $this->belongsTo("App\Models\Lophoc","lop_id"); // TODO: Change the autogenerated stub
    }

}
