<?php

namespace App\Http\Controllers\Quantri\phancong;

use App\Models\Phancong;
use App\Models\Student;
use App\Models\Teacher;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use DateTime;
use Illuminate\Support\Facades\DB;

class listController extends Controller
{
    public function listPC()
    {
        $hv=Student::get()->toArray();
        $data=DB::table('giasu_phancong')
            ->join('giasu_hocvien','giasu_phancong.hv_id','=','giasu_hocvien.id')
            ->join('giasu_giaovien','giasu_phancong.gv_id','=','giasu_giaovien.id')
            ->select('giasu_hocvien.name as tenhv','giasu_giaovien.name as tengv','giasu_phancong.*')
            ->get();
        //echo "<pre>";print_r($data);echo "</pre>";
        return view('quantri.phancong.list',['hv'=>$hv,'data'=>$data]); // TODO: Change the autogenerated stub
    }
    public function addPC(Request $request)
    {
        $pc=new Phancong();
        $pc->hv_id=$request->hv_id;
        $pc->mon_hoc=$request->mon_hoc;
        $pc->gv_id=$request->gv_id;
        $pc->ngay_bd=$request->ngay_bd;
        $pc->money=$request->money;
        $pc->sobuoi=$request->sobuoi;
        $pc->more=$request->more;
        $pc->created_at=new DateTime;
        $pc->save();
        $hv=Student::find($request->hv_id);
        $hv->status=0;
        $hv->save();
        $gv=Teacher::find($request->gv_id);
        $gv->status=1;
        $gv->save();
        return redirect()->route('listPC')->with(['flash_level'=>'result_msg','flash_message'=>'Add item success']);
        // TODO: Change the autogenerated stub
    }
    public function detail($id)
    {
        $data=DB::table('giasu_phancong')->where('giasu_phancong.id','=',$id)
        ->join('giasu_hocvien','giasu_phancong.hv_id','=','giasu_hocvien.id')
        ->join('giasu_giaovien','giasu_phancong.gv_id','=','giasu_giaovien.id')
        ->select('giasu_hocvien.name as tenhv','giasu_giaovien.name as tengv','giasu_phancong.*')
        ->get();
        //echo "<pre>";print_r($data);echo "</pre>";
        return view('quantri.phancong.detail',['data'=>$data,'id'=>$id]); // TODO: Change the autogenerated stub
    }
    public function edit($id, Request $request)
    {
        $pc=Phancong::find($id);
        $pc->trangthai=$request->trangthai;
        $pc->more=$request->more;
        $pc->status=$request->status;
        $pc->save();
        if($request->trangthai==0 && $request->status==1){
            $hv=Student::find($request->hv_id);
            $hv->status=2;
            $hv->save();
            $gv=Teacher::find($request->gv_id);
            $gv->status=0;
            $gv->save();
        }else{
            $hv=Student::find($request->hv_id);
            $hv->status=0;
            $hv->save();
            $gv=Teacher::find($request->gv_id);
            $gv->status=1;
            $gv->save();
        }
        return redirect()->route('listPC')->with(['flash_level'=>'result_msg','flash_message'=>'Edit item success !']);// TODO: Change the autogenerated stub
    }
    public function delete($id)
    {
        $pc=Phancong::find($id);
        $pc->delete();
        return redirect()->route('listPC')->with(['flash_level'=>'result_msg','flash_message'=>'Delete item success']);
        // TODO: Change the autogenerated stub
    }
}
